version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ems
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - ems-network



  backend:
    build: .
    container_name: ems-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ems-network


  frontend:
        build:
          context: ../../ems-frontend   # IMPORTANT (adjust if needed)
        container_name: ems-frontend
        ports:
          - "3000:80"
        depends_on:
          - backend
        networks:
          - ems-network

networks:
      ems-network:
volumes:
  mysql-data:
